import type {
  Alert,
  Incident,
  MapPin,
  Notification,
  Resource,
  ResourceAssignment,
  Responder,
  Shelter,
  Task,
  User,
} from "./types";

/**
 * Fictional demo data for the SURAKSHA360 prototype.
 * District, wards, teams and people are invented — nothing here is real.
 */

const T = (h: number, m = 0) => {
  const d = new Date("2026-09-05T00:00:00Z");
  d.setUTCHours(h, m, 0, 0);
  return d.toISOString();
};

export const seedUsers: User[] = [
  { id: "USR-001", name: "Ananya Rao", role: "citizen", phone: "+91 90000 11001", ward: "Ward 12 — Riverside" },
  { id: "USR-002", name: "Control Room — Dist. Officer", role: "authority", phone: "+91 90000 11002", ward: "Nagara District EOC" },
  { id: "USR-003", name: "Capt. Vikram Sethi", role: "responder", phone: "+91 90000 11003", ward: "Rescue Team Alpha" },
];

export const CITIZEN = seedUsers[0]!;
export const AUTHORITY = seedUsers[1]!;
export const RESPONDER = seedUsers[2]!;

export const seedResponders: Responder[] = [
  {
    id: "RSP-01",
    name: "Capt. Vikram Sethi",
    team: "Rescue Team Alpha",
    specialisation: "Swift-water rescue",
    phone: "+91 90000 22001",
    baseStation: "Riverside Fire Station",
    available: false,
    completedMissions: 47,
  },
  {
    id: "RSP-02",
    name: "Dr. Meera Iyer",
    team: "Medical Unit Bravo",
    specialisation: "Field triage & first aid",
    phone: "+91 90000 22002",
    baseStation: "Nagara Civil Hospital",
    available: true,
    completedMissions: 31,
  },
  {
    id: "RSP-03",
    name: "Imran Qureshi",
    team: "Fire Squad Charlie",
    specialisation: "Fire suppression",
    phone: "+91 90000 22003",
    baseStation: "Central Fire Station",
    available: true,
    completedMissions: 62,
  },
  {
    id: "RSP-04",
    name: "Sgt. Kavya Menon",
    team: "Evacuation Unit Delta",
    specialisation: "Crowd movement & shelters",
    phone: "+91 90000 22004",
    baseStation: "Ward 7 Depot",
    available: true,
    completedMissions: 24,
  },
  {
    id: "RSP-05",
    name: "Rohit Barman",
    team: "Volunteer Corps Echo",
    specialisation: "Relief distribution",
    phone: "+91 90000 22005",
    baseStation: "Community Hall, Ward 12",
    available: true,
    completedMissions: 18,
  },
];

export const seedResources: Resource[] = [
  { id: "RES-01", name: "Dry ration kits", category: "Food", unit: "kits", total: 900, assigned: 260, depot: "Central Relief Depot" },
  { id: "RES-02", name: "Cooked meal packets", category: "Food", unit: "packets", total: 1400, assigned: 480, depot: "Ward 7 Kitchen" },
  { id: "RES-03", name: "Drinking water cans (20L)", category: "Water", unit: "cans", total: 620, assigned: 210, depot: "Central Relief Depot" },
  { id: "RES-04", name: "Water purification tablets", category: "Water", unit: "strips", total: 3000, assigned: 640, depot: "Health Store" },
  { id: "RES-05", name: "Emergency medicine kits", category: "Medicines", unit: "kits", total: 240, assigned: 88, depot: "Nagara Civil Hospital" },
  { id: "RES-06", name: "ORS & IV fluids", category: "Medicines", unit: "boxes", total: 410, assigned: 120, depot: "Health Store" },
  { id: "RES-07", name: "Woollen blankets", category: "Blankets", unit: "pieces", total: 1100, assigned: 350, depot: "Ward 12 Store" },
  { id: "RES-08", name: "Ambulances (ALS)", category: "Ambulances", unit: "vehicles", total: 12, assigned: 5, depot: "Civil Hospital Bay" },
  { id: "RES-09", name: "Inflatable rescue boats", category: "Rescue Equipment", unit: "boats", total: 16, assigned: 7, depot: "Riverside Fire Station" },
  { id: "RES-10", name: "Life jackets & ropes", category: "Rescue Equipment", unit: "sets", total: 300, assigned: 96, depot: "Riverside Fire Station" },
];

export const seedIncidents: Incident[] = [
  {
    id: "INC-2026-1042",
    type: "Flood",
    severity: "critical",
    status: "in_progress",
    location: "Riverside Colony, Ward 12",
    lat: 10.012,
    lng: 76.281,
    description:
      "Embankment breach near the pump house. Ground floors submerged, roughly 12 residents including 3 children stranded on rooftops.",
    affectedPeople: 12,
    imageName: "riverside-breach.jpg",
    reportedBy: CITIZEN.name,
    reportedById: CITIZEN.id,
    reportedAt: T(5, 40),
    verifiedBy: AUTHORITY.name,
    timeline: [
      { status: "reported", label: "Reported by citizen", at: T(5, 40), by: CITIZEN.name },
      { status: "verification", label: "Under verification", at: T(5, 48), by: AUTHORITY.name },
      { status: "verified", label: "Verified — ward officer confirmed breach", at: T(5, 55), by: AUTHORITY.name },
      { status: "assigned", label: "Assigned to Rescue Team Alpha", at: T(6, 2), by: AUTHORITY.name },
      { status: "in_progress", label: "Rescue underway, boats deployed", at: T(6, 25), by: "Rescue Team Alpha" },
    ],
  },
  {
    id: "INC-2026-1041",
    type: "Fire",
    severity: "high",
    status: "assigned",
    location: "Timber Market, Ward 4",
    lat: 9.978,
    lng: 76.315,
    description: "Godown fire spreading to adjacent sheds. Heavy smoke reported across the market lane.",
    affectedPeople: 30,
    reportedBy: "Sunil Kalita",
    reportedById: "USR-014",
    reportedAt: T(4, 15),
    verifiedBy: AUTHORITY.name,
    timeline: [
      { status: "reported", label: "Reported by citizen", at: T(4, 15), by: "Sunil Kalita" },
      { status: "verified", label: "Verified by control room", at: T(4, 26), by: AUTHORITY.name },
      { status: "assigned", label: "Assigned to Fire Squad Charlie", at: T(4, 33), by: AUTHORITY.name },
    ],
  },
  {
    id: "INC-2026-1040",
    type: "Landslide",
    severity: "critical",
    status: "verified",
    location: "Hill Road bend, Ward 9",
    lat: 10.041,
    lng: 76.253,
    description: "Slope collapse has blocked both lanes. Two vehicles trapped behind the debris line.",
    affectedPeople: 8,
    reportedBy: "Ward Patrol Unit",
    reportedById: "USR-021",
    reportedAt: T(3, 5),
    verifiedBy: AUTHORITY.name,
    timeline: [
      { status: "reported", label: "Reported by ward patrol", at: T(3, 5), by: "Ward Patrol Unit" },
      { status: "verification", label: "Under verification", at: T(3, 12), by: AUTHORITY.name },
      { status: "verified", label: "Verified — awaiting team allocation", at: T(3, 30), by: AUTHORITY.name },
    ],
  },
  {
    id: "INC-2026-1039",
    type: "Building Collapse",
    severity: "high",
    status: "verification",
    location: "Old Bazaar Street, Ward 2",
    lat: 9.991,
    lng: 76.268,
    description: "Two-storey structure partially collapsed after continuous rain. Neighbours suspect people inside.",
    affectedPeople: 5,
    reportedBy: "Farhan Sheikh",
    reportedById: "USR-032",
    reportedAt: T(2, 50),
    timeline: [
      { status: "reported", label: "Reported by citizen", at: T(2, 50), by: "Farhan Sheikh" },
      { status: "verification", label: "Under verification", at: T(2, 58), by: AUTHORITY.name },
    ],
  },
  {
    id: "INC-2026-1038",
    type: "Flood",
    severity: "medium",
    status: "reported",
    location: "Lakeview Lane, Ward 15",
    lat: 10.028,
    lng: 76.336,
    description: "Storm drain overflow, knee-deep water on the approach road to the school.",
    affectedPeople: 20,
    reportedBy: "Nisha Pillai",
    reportedById: "USR-041",
    reportedAt: T(7, 5),
    timeline: [{ status: "reported", label: "Reported by citizen", at: T(7, 5), by: "Nisha Pillai" }],
  },
  {
    id: "INC-2026-1037",
    type: "Heatwave",
    severity: "medium",
    status: "in_progress",
    location: "Bus Terminal, Ward 6",
    lat: 9.965,
    lng: 76.291,
    description: "Multiple heat-exhaustion cases among waiting commuters. ORS counter requested.",
    affectedPeople: 14,
    reportedBy: "Terminal Supervisor",
    reportedById: "USR-055",
    reportedAt: T(1, 20),
    verifiedBy: AUTHORITY.name,
    timeline: [
      { status: "reported", label: "Reported by terminal staff", at: T(1, 20), by: "Terminal Supervisor" },
      { status: "verified", label: "Verified by control room", at: T(1, 35), by: AUTHORITY.name },
      { status: "assigned", label: "Assigned to Medical Unit Bravo", at: T(1, 45), by: AUTHORITY.name },
      { status: "in_progress", label: "ORS counter operational", at: T(2, 10), by: "Medical Unit Bravo" },
    ],
  },
  {
    id: "INC-2026-1036",
    type: "Cyclone",
    severity: "high",
    status: "resolved",
    location: "Fishermen's Wharf, Ward 18",
    lat: 10.003,
    lng: 76.344,
    description: "Wind damage to 9 boat sheds ahead of Cyclone Meghna landfall. Families moved to shelter.",
    affectedPeople: 42,
    reportedBy: "Harbour Warden",
    reportedById: "USR-063",
    reportedAt: T(0, 30),
    verifiedBy: AUTHORITY.name,
    timeline: [
      { status: "reported", label: "Reported by harbour warden", at: T(0, 30), by: "Harbour Warden" },
      { status: "verified", label: "Verified by control room", at: T(0, 40), by: AUTHORITY.name },
      { status: "assigned", label: "Assigned to Evacuation Unit Delta", at: T(0, 50), by: AUTHORITY.name },
      { status: "in_progress", label: "Evacuation in progress", at: T(1, 5), by: "Evacuation Unit Delta" },
      { status: "resolved", label: "42 people sheltered, area secured", at: T(2, 40), by: "Evacuation Unit Delta" },
    ],
  },
  {
    id: "INC-2026-1035",
    type: "Earthquake",
    severity: "low",
    status: "rejected",
    location: "Green Park, Ward 11",
    lat: 9.985,
    lng: 76.302,
    description: "Reported tremors — later traced to nearby construction piling work.",
    affectedPeople: 0,
    reportedBy: "Anonymous",
    reportedById: "USR-070",
    reportedAt: T(0, 10),
    rejectionReason: "Field check found construction vibration, no seismic event.",
    timeline: [
      { status: "reported", label: "Reported by citizen", at: T(0, 10), by: "Anonymous" },
      { status: "verification", label: "Under verification", at: T(0, 18), by: AUTHORITY.name },
      { status: "rejected", label: "Rejected — construction vibration", at: T(0, 35), by: AUTHORITY.name },
    ],
  },
];

export const seedTasks: Task[] = [
  {
    id: "TSK-501",
    incidentId: "INC-2026-1042",
    title: "Rooftop evacuation — Riverside Colony",
    responderId: "RSP-01",
    teamName: "Rescue Team Alpha",
    status: "in_progress",
    priority: "critical",
    instructions:
      "Deploy 2 inflatable boats from the pump house side. Prioritise 3 children and 1 elderly resident. Coordinate handover with Medical Unit Bravo at the Ward 12 community hall.",
    location: "Riverside Colony, Ward 12",
    assignedBy: AUTHORITY.name,
    assignedAt: T(6, 2),
    timeline: [
      { status: "assigned", label: "Task assigned", at: T(6, 2), by: AUTHORITY.name },
      { status: "accepted", label: "Accepted by team lead", at: T(6, 6), by: "Capt. Vikram Sethi" },
      { status: "on_the_way", label: "En route with 2 boats", at: T(6, 12), by: "Capt. Vikram Sethi" },
      { status: "arrived", label: "Arrived at breach point", at: T(6, 20), by: "Capt. Vikram Sethi" },
      { status: "in_progress", label: "Evacuation underway", at: T(6, 25), by: "Capt. Vikram Sethi" },
    ],
  },
  {
    id: "TSK-502",
    incidentId: "INC-2026-1041",
    title: "Fire suppression — Timber Market godown",
    responderId: "RSP-03",
    teamName: "Fire Squad Charlie",
    status: "accepted",
    priority: "high",
    instructions: "Two tenders from Central Station. Create a firebreak on the eastern shed row before entry.",
    location: "Timber Market, Ward 4",
    assignedBy: AUTHORITY.name,
    assignedAt: T(4, 33),
    timeline: [
      { status: "assigned", label: "Task assigned", at: T(4, 33), by: AUTHORITY.name },
      { status: "accepted", label: "Accepted by squad lead", at: T(4, 38), by: "Imran Qureshi" },
    ],
  },
  {
    id: "TSK-503",
    incidentId: "INC-2026-1037",
    title: "Heat relief counter — Bus Terminal",
    responderId: "RSP-02",
    teamName: "Medical Unit Bravo",
    status: "in_progress",
    priority: "medium",
    instructions: "Run ORS and cooling station at gate 3. Refer severe cases to Civil Hospital.",
    location: "Bus Terminal, Ward 6",
    assignedBy: AUTHORITY.name,
    assignedAt: T(1, 45),
    timeline: [
      { status: "assigned", label: "Task assigned", at: T(1, 45), by: AUTHORITY.name },
      { status: "accepted", label: "Accepted", at: T(1, 50), by: "Dr. Meera Iyer" },
      { status: "on_the_way", label: "Team moving to terminal", at: T(1, 55), by: "Dr. Meera Iyer" },
      { status: "arrived", label: "Counter set up at gate 3", at: T(2, 5), by: "Dr. Meera Iyer" },
      { status: "in_progress", label: "Treating heat-exhaustion cases", at: T(2, 10), by: "Dr. Meera Iyer" },
    ],
  },
  {
    id: "TSK-504",
    incidentId: "INC-2026-1036",
    title: "Shelter shift — Fishermen's Wharf",
    responderId: "RSP-04",
    teamName: "Evacuation Unit Delta",
    status: "completed",
    priority: "high",
    instructions: "Move 42 residents to Coastal Guard Hall. Log family units at intake desk.",
    location: "Fishermen's Wharf, Ward 18",
    assignedBy: AUTHORITY.name,
    assignedAt: T(0, 50),
    timeline: [
      { status: "assigned", label: "Task assigned", at: T(0, 50), by: AUTHORITY.name },
      { status: "accepted", label: "Accepted", at: T(0, 55), by: "Sgt. Kavya Menon" },
      { status: "on_the_way", label: "Buses dispatched", at: T(1, 0), by: "Sgt. Kavya Menon" },
      { status: "arrived", label: "Arrived at wharf", at: T(1, 5), by: "Sgt. Kavya Menon" },
      { status: "in_progress", label: "Boarding families", at: T(1, 15), by: "Sgt. Kavya Menon" },
      { status: "completed", label: "42 residents sheltered", at: T(2, 40), by: "Sgt. Kavya Menon" },
    ],
  },
  {
    id: "TSK-505",
    incidentId: "INC-2026-1040",
    title: "Debris clearance survey — Hill Road",
    responderId: "RSP-05",
    teamName: "Volunteer Corps Echo",
    status: "assigned",
    priority: "critical",
    instructions: "Assess debris volume, mark safe standoff line and report equipment needs to EOC.",
    location: "Hill Road bend, Ward 9",
    assignedBy: AUTHORITY.name,
    assignedAt: T(3, 40),
    timeline: [{ status: "assigned", label: "Task assigned", at: T(3, 40), by: AUTHORITY.name }],
  },
];

export const seedResourceAssignments: ResourceAssignment[] = [
  { id: "RA-01", resourceId: "RES-09", incidentId: "INC-2026-1042", quantity: 2, assignedBy: AUTHORITY.name, assignedAt: T(6, 3) },
  { id: "RA-02", resourceId: "RES-03", incidentId: "INC-2026-1042", quantity: 40, assignedBy: AUTHORITY.name, assignedAt: T(6, 8) },
  { id: "RA-03", resourceId: "RES-01", incidentId: "INC-2026-1042", quantity: 30, assignedBy: AUTHORITY.name, assignedAt: T(6, 9) },
  { id: "RA-04", resourceId: "RES-08", incidentId: "INC-2026-1042", quantity: 2, assignedBy: AUTHORITY.name, assignedAt: T(6, 10) },
  { id: "RA-05", resourceId: "RES-05", incidentId: "INC-2026-1037", quantity: 6, assignedBy: AUTHORITY.name, assignedAt: T(1, 50) },
  { id: "RA-06", resourceId: "RES-07", incidentId: "INC-2026-1036", quantity: 60, assignedBy: AUTHORITY.name, assignedAt: T(1, 10) },
];

export const seedAlerts: Alert[] = [
  {
    id: "ALT-01",
    title: "Red alert — embankment breach, Ward 12",
    severity: "critical",
    area: "Riverside Colony & Pump House Road",
    message: "Water level rising 15 cm/hour after the embankment breach. Ground floors already submerged.",
    action: "Move to the first floor or to Ward 12 Community Shelter immediately. Do not cross flowing water.",
    issuedBy: "Nagara District EOC",
    issuedAt: T(5, 58),
    demo: true,
  },
  {
    id: "ALT-02",
    title: "Cyclone Meghna — coastal wind warning",
    severity: "high",
    area: "Wards 16–18, coastal belt",
    message: "Sustained winds of 95 km/h expected between 14:00 and 20:00 with gusts up to 120 km/h.",
    action: "Secure loose roofing, keep boats docked, stay indoors after 13:00.",
    issuedBy: "Nagara District EOC",
    issuedAt: T(4, 0),
    demo: true,
  },
  {
    id: "ALT-03",
    title: "Hill Road closed — landslide debris",
    severity: "high",
    area: "Ward 9, Hill Road bend km 4",
    message: "Both lanes blocked by slope collapse. Clearance expected to take 6–8 hours.",
    action: "Use the Ward 8 bypass via Temple Road. Avoid slope-side parking.",
    issuedBy: "Traffic & Roads Cell",
    issuedAt: T(3, 20),
    demo: true,
  },
  {
    id: "ALT-04",
    title: "Heat advisory — afternoon hours",
    severity: "medium",
    area: "District-wide",
    message: "Apparent temperature likely to reach 42°C between 12:00 and 16:00.",
    action: "Avoid outdoor work at noon, drink water every 30 minutes, check on elderly neighbours.",
    issuedBy: "Health Department",
    issuedAt: T(2, 0),
    demo: true,
  },
  {
    id: "ALT-05",
    title: "Boil-water notice — Ward 15",
    severity: "medium",
    area: "Lakeview Lane and adjoining streets",
    message: "Storm drain overflow may have contaminated the local supply line.",
    action: "Boil drinking water or use the purification tablets distributed at the ward office.",
    issuedBy: "Water Authority",
    issuedAt: T(7, 15),
    demo: true,
  },
];

export const seedShelters: Shelter[] = [
  { id: "SHL-01", name: "Ward 12 Community Shelter", location: "Riverside Colony, Ward 12", capacity: 400, occupied: 268, food: true, medical: true, accessible: true, contact: "+91 90000 33001", lat: 10.008, lng: 76.29 },
  { id: "SHL-02", name: "Govt. Higher Secondary School", location: "Bazaar Road, Ward 2", capacity: 650, occupied: 310, food: true, medical: false, accessible: true, contact: "+91 90000 33002", lat: 9.994, lng: 76.264 },
  { id: "SHL-03", name: "Coastal Guard Hall", location: "Fishermen's Wharf, Ward 18", capacity: 300, occupied: 288, food: true, medical: true, accessible: false, contact: "+91 90000 33003", lat: 10.001, lng: 76.34 },
  { id: "SHL-04", name: "Hill View Municipal Hall", location: "Temple Road, Ward 9", capacity: 220, occupied: 74, food: false, medical: true, accessible: true, contact: "+91 90000 33004", lat: 10.038, lng: 76.256 },
  { id: "SHL-05", name: "Lakeview Sports Complex", location: "Lakeview Lane, Ward 15", capacity: 520, occupied: 96, food: true, medical: false, accessible: true, contact: "+91 90000 33005", lat: 10.026, lng: 76.331 },
  { id: "SHL-06", name: "Terminal Relief Camp", location: "Bus Terminal, Ward 6", capacity: 180, occupied: 155, food: true, medical: true, accessible: true, contact: "+91 90000 33006", lat: 9.967, lng: 76.294 },
];

export const seedMapPins: MapPin[] = [
  { id: "MP-01", kind: "hospital", name: "Nagara Civil Hospital", detail: "Trauma + ICU, 40 beds free", lat: 9.997, lng: 76.279 },
  { id: "MP-02", kind: "hospital", name: "Lakeview Health Centre", detail: "Primary care, 12 beds free", lat: 10.031, lng: 76.327 },
  { id: "MP-03", kind: "fire_station", name: "Riverside Fire Station", detail: "3 tenders, 2 boats ready", lat: 10.015, lng: 76.274 },
  { id: "MP-04", kind: "fire_station", name: "Central Fire Station", detail: "2 tenders deployed", lat: 9.982, lng: 76.308 },
  { id: "MP-05", kind: "blocked_road", name: "Hill Road bend km 4", detail: "Landslide debris — closed", lat: 10.043, lng: 76.251 },
  { id: "MP-06", kind: "blocked_road", name: "Pump House Road", detail: "Waterlogged 1.2 m — closed", lat: 10.014, lng: 76.286 },
];

export const seedNotifications: Notification[] = [
  {
    id: "NTF-01",
    incidentId: "INC-2026-1036",
    title: "Incident INC-2026-1036 resolved",
    body: "Evacuation Unit Delta sheltered all 42 residents from Fishermen's Wharf. Thank you for reporting.",
    at: T(2, 41),
    audience: "citizen",
    read: false,
  },
  {
    id: "NTF-02",
    incidentId: "INC-2026-1042",
    title: "Rescue Team Alpha is on site",
    body: "Your report INC-2026-1042 was verified and a rescue team is evacuating residents by boat.",
    at: T(6, 25),
    audience: "citizen",
    read: false,
  },
];
